feat: implement test views, questions actions
Kroch4ka/test_guru pull request #8
Opened 2023-01-27 17:16 UTC by Kroch4ka

2023-01-27 18:14 UTC, BubuntuClu requested changes

2023-01-27 18:14 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
возвращай тут сразу хэлпер `link_to`, чтобы был какой-то смысл в методе. сейчас тут просто подставляются строки в строку, что выглядит странно

2023-01-27 18:14 UTC, BubuntuClu commented on app/models/question.rb
> +  has_many :answers, :dependent => :delete_all
1 - используй обновленный синтаксис `dependent: delete_all`
2 - почему ты выбрал именно `delete_all`? поняли ли ты в чем разница между другими опциями?

2023-01-27 18:14 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :questions, :dependent => :delete_all
аналогично и тут

2023-01-27 18:14 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +  <h1><%= question_form_header(@question) %></h1>
если делать общий метод, но приэтом вызывать его на конкретной вьюхе, то смысла в общем методе нет, можно напрямую во вьюхе указать нужный заголовок. тут смысл как раз в том чтобы этого не делать, а в `_form` вызывать метод и он сам определит какой текст отобразить

по сути код вьюх `edit/new` будет одинаковый, с вызовом формы `<%= render 'form', question: @question, test: @test %>`, но ты еще добавил обертку с именем класса на див, что чуть удленит код во вьюхах, не так страшно

2023-01-27 18:14 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<div class="edit_question">
если тебе нужно подчеркнуть уникальность какого-то элемента то задавай ему `id`, классы в итоге разработки приложения могут начать пересекаться и тут может начаться магия с их отображением

2023-01-27 18:14 UTC, BubuntuClu commented on app/views/shared/_footer.html.erb
> +</footer>
видишь тут красный знак нарисован у последней строки? это ругается гитхаб, что нет пустой строки в конце файла. в IDE сделай настройку, чтобы добавлялась пустая строка в конец файла. Это исправит ворнинг на гитхабе

2023-01-27 18:14 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def index
этот метод тебе больше не нужен

2023-01-28 17:45 UTC, BubuntuClu commented on app/models/test.rb
> -  belongs_to :creator, foreign_key: :creator_id, class_name: :User
creator_id надо оставить. у тебя связь по этому столбцу происходит. без него не должна работать эта ассоциация

2023-01-28 17:58 UTC, Kroch4ka commented on app/models/test.rb
> -  belongs_to :creator, foreign_key: :creator_id, class_name: :User
Эт у меня rubocop гад удалил)) Поправлю)

2023-01-28 19:11 UTC, merged